version: "2"
services:
  chirpstack-gateway-bridge:
    build:
      context: ./chirpstack-gateway-bridge
      dockerfile: Dockerfile-devel
    ports:
      - "1700:1700/udp"
    volumes:
      - balena-data:/chirpstack-gateway-bridge
    links:
      - mosquitto
    environment:
      - MQTT_SERVER=tcp://mosquitto:1883
      - TEST_MQTT_SERVER=tcp://mosquitto:1883

  mosquitto:
    image: eclipse-mosquitto

  chirpstack-application-server:
    build: 
      context: ./chirpstack-application-server
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/chirpstack-application-server
      # - ../chirpstack-api:/chirpstack-api
    links:
      - postgres
      - redis
      - mosquitto1
      - rabbitmq
      - zookeeper
      - kafka
    environment:
      - TEST_POSTGRES_DSN=postgres://chirpstack_as:chirpstack_as@postgres/chirpstack_as?sslmode=disable
      - TEST_REDIS_SERVERS=redis:6379
      - TEST_MQTT_SERVER=tcp://mosquitto:1883
      - TEST_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - TEST_KAFKA_BROKER=kafka:9092

  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:4-alpine

  mosquitto1:
    image: eclipse-mosquitto

  rabbitmq:
    image: rabbitmq:3-alpine

  zookeeper:
    image: 'bitnami/zookeeper:3'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  chirpstack-network-server:
    build:
      context: ./chirpstack-network-server
      dockerfile: Dockerfile-devel
    command: make serve
    volumes:
      - balena-data:/chirpstack-network-server
    links:
      - postgres1
      - redis1
      - mosquitto2
      - rabbitmq1
    environment:
      - DB_AUTOMIGRATE=true
      - NET_ID=010203
      - BAND=EU868
      - REDIS_URL=redis://redis:6379
      - GW_MQTT_SERVER=tcp://mosquitto:1883
      - GW_SERVER_JWT_SECRET=verysecret
      - POSTGRES_DSN=postgres://chirpstack_ns:chirpstack_ns@postgres/chirpstack_ns?sslmode=disable
      - TEST_POSTGRES_DSN=postgres://chirpstack_ns:chirpstack_ns@postgres/chirpstack_ns?sslmode=disable
      - TEST_REDIS_SERVERS=redis:6379
      - TEST_MQTT_SERVER=tcp://mosquitto:1883
      - TEST_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  postgres1:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=chirpstack_ns
      - POSTGRES_USER=chirpstack_ns
      - POSTGRES_DB=chirpstack_ns

  redis1:
    image: redis:3.0.7-alpine

  mosquitto2:
    image: ansi/mosquitto

  rabbitmq1:
    image: rabbitmq:3-alpine

volumes:
    balena-data:
